apiVersion: v1
kind: Service
metadata:
  name: rcloneproxy
  labels:
    app: rcloneproxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    app: rcloneproxy
