apiVersion: v1
kind: Service
metadata:
  name: {{ include "rcloneproxy.fullname" . }}
  labels:
    {{- include "rcloneproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    {{- include "rcloneproxy.selectorLabels" . | nindent 4 }}
