{{ if .Values.backups.enabled }}
{{ $context := . -}}
{{ range .Values.backups.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.fullname" $context  }}-{{ .name }}
  namespace: {{ include "cluster.namespace" $ }}
  labels: {{ include "cluster.labels" $context | nindent 4 }}
spec:
  {{- if .immediate }}
  immediate: {{ .immediate }}
  {{- else }}
  immediate: true
  {{- end }}
  schedule: {{ .schedule | quote }}
  {{- if eq $context.Values.backups.method "plugin" }}
  method: plugin
  cluster:
    name: {{ include "cluster.fullname" $context }}
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: {{ printf "%s-objectstore" $context.Release.Name }}
  {{- else }}
  method: {{ $context.Values.backups.method }}
  backupOwnerReference: {{ .backupOwnerReference }}
  cluster:
    name: {{ include "cluster.fullname" $context }}
  {{- end }}
{{ end -}}
{{ end }}
